---
- name: Run Docker Compose
  hosts: localhost
  remote_user: harsh
  connection: local
  gather_facts: no
  tasks:
    - name: Run Docker Compose
      command: docker-compose up
      args:
        chdir: /var/lib/jenkins/workspace/SPE_FINAL_PROJECT

